package schema

import (
	"cloud.google.com/go/bigquery"
)

var (
	// AnnotationSchema is the table schema for annotation.
	AnnotationSchema = bigquery.Schema{
		{Name: "CHROM", Required: true, Type: bigquery.StringFieldType},
		{Name: "POS", Required: true, Type: bigquery.IntegerFieldType},
		{Name: "ID", Type: bigquery.StringFieldType},
		{Name: "REF", Required: true, Type: bigquery.StringFieldType},
		{Name: "ALT", Required: true, Type: bigquery.StringFieldType},
		{Name: "QUAL", Type: bigquery.FloatFieldType},
		{Name: "FILTER", Type: bigquery.StringFieldType},
		{Name: "GQ", Type: bigquery.FloatFieldType},
		{Name: "DP", Type: bigquery.IntegerFieldType},
		{Name: "RD", Type: bigquery.IntegerFieldType},
		{Name: "AD", Type: bigquery.IntegerFieldType},
		{Name: "GT", Type: bigquery.StringFieldType},
		{Name: "PS", Type: bigquery.StringFieldType},
		{Name: "GT_AF", Type: bigquery.FloatFieldType},
		{Name: "VARIANT_CLASS", Type: bigquery.StringFieldType},
		{Name: "Allele", Type: bigquery.StringFieldType},
		{Name: "Consequence", Type: bigquery.StringFieldType},
		{Name: "IMPACT", Type: bigquery.StringFieldType},
		{Name: "SYMBOL", Type: bigquery.StringFieldType},
		{Name: "Gene", Type: bigquery.StringFieldType},
		{Name: "Feature_type", Type: bigquery.StringFieldType},
		{Name: "Feature", Type: bigquery.StringFieldType},
		{Name: "BioType", Type: bigquery.StringFieldType},
		{Name: "Rank", Type: bigquery.StringFieldType},
		{Name: "HGVSc", Type: bigquery.StringFieldType},
		{Name: "HGVSp", Type: bigquery.StringFieldType},
		{Name: "cDNA_position", Type: bigquery.StringFieldType},
		{Name: "CDS_position", Type: bigquery.StringFieldType},
		{Name: "Protein_position", Type: bigquery.StringFieldType},
		{Name: "Distance", Type: bigquery.IntegerFieldType},
		{Name: "ERRORS_WARNINGS_INFO", Type: bigquery.StringFieldType},
		{Name: "gnomAD_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_AFR_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_AMR_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_ASJ_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_EAS_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_FIN_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_NFE_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_OTH_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_SAS_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_ANR_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_AMR_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_ASJ_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_EAS_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_FIN_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_NFE_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_OTH_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_SAS_AN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_cov_MEAN", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_cov_MEDIAN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_cov_PCT_20X", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_cov_MEAN", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_cov_MEDIAN", Type: bigquery.IntegerFieldType},
		{Name: "gnomAD_g_cov_PCT_20X", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_AF_hom", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_afr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_ami", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_amr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_asj", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_eas", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_fin", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_nfe", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_oth", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_sas", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_hom_mid", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_AF_het", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_afr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_ami", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_amr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_asj", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_eas", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_fin", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_nfe", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_oth", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_sas", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_pop_AF_het_mid", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_mt_mitotip_score", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_afr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_ami", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_amr", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_asj", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_eas", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_fin", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_mid", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_nfe", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_oth", Type: bigquery.FloatFieldType},
		{Name: "gnomAD_g_AF_sas", Type: bigquery.FloatFieldType},
		{Name: "ada_score", Type: bigquery.FloatFieldType},
		{Name: "rf_score", Type: bigquery.FloatFieldType},
		{Name: "SpliceAI_DS_AG", Type: bigquery.FloatFieldType},
		{Name: "SpliceAI_DS_AL", Type: bigquery.FloatFieldType},
		{Name: "SpliceAI_DS_DG", Type: bigquery.FloatFieldType},
		{Name: "SpliceAI_DS_DL", Type: bigquery.FloatFieldType},
		{Name: "SpliceAI_DP_AG", Type: bigquery.IntegerFieldType},
		{Name: "SpliceAI_DP_AL", Type: bigquery.IntegerFieldType},
		{Name: "SpliceAI_DP_DG", Type: bigquery.IntegerFieldType},
		{Name: "SpliceAI_DP_DL", Type: bigquery.IntegerFieldType},
		{Name: "SIFT_score", Type: bigquery.FloatFieldType},
		{Name: "SIFT_pred", Type: bigquery.StringFieldType},
		{Name: "SIFT4G_score", Type: bigquery.FloatFieldType},
		{Name: "SIFT4G_pred", Type: bigquery.StringFieldType},
		{Name: "MetaLR_score", Type: bigquery.FloatFieldType},
		{Name: "MetaLR_pred", Type: bigquery.StringFieldType},
		{Name: "MetaSVM_score", Type: bigquery.FloatFieldType},
		{Name: "MetaSVM_pred", Type: bigquery.StringFieldType},
		{Name: "REVEL_score", Type: bigquery.FloatFieldType},
		{Name: "Polyphen", Type: bigquery.FloatFieldType},
		{Name: "Polyphen_pred", Type: bigquery.StringFieldType},
		{Name: "FATHMM_score", Type: bigquery.FloatFieldType},
		{Name: "FATHMM_pred", Type: bigquery.StringFieldType},
		{Name: "MutationAssessor_score", Type: bigquery.FloatFieldType},
		{Name: "MutationAssessor_pred", Type: bigquery.StringFieldType},
		{Name: "PROVEAN_score", Type: bigquery.FloatFieldType},
		{Name: "PROVEAN_pred", Type: bigquery.StringFieldType},
		{Name: "CADD_raw", Type: bigquery.FloatFieldType},
		{Name: "CADD_phred", Type: bigquery.FloatFieldType},
		{Name: "M_CAP_score", Type: bigquery.FloatFieldType},
		{Name: "M_CAP_pred", Type: bigquery.StringFieldType},
		{Name: "REVEL_rankscore", Type: bigquery.FloatFieldType},
		{Name: "ESP6500_AA_AF", Type: bigquery.FloatFieldType},
		{Name: "ESP6500_EA_AF", Type: bigquery.FloatFieldType},
		{Name: "BayesDel_addAF_score", Type: bigquery.FloatFieldType},
		{Name: "BayesDel_addAF_pred", Type: bigquery.StringFieldType},
		{Name: "GERPpp_NR", Type: bigquery.FloatFieldType},
		{Name: "GERPpp_RS", Type: bigquery.FloatFieldType},
		{Name: "SiPhy_29way_logOdds", Type: bigquery.FloatFieldType},
		{Name: "SiPhy_29way_pi", Type: bigquery.StringFieldType},
		{Name: "oe_syn", Type: bigquery.FloatFieldType},
		{Name: "oe_mis", Type: bigquery.FloatFieldType},
		{Name: "oe_lof", Type: bigquery.FloatFieldType},
		{Name: "syn_z", Type: bigquery.FloatFieldType},
		{Name: "mis_z", Type: bigquery.FloatFieldType},
		{Name: "pLI", Type: bigquery.FloatFieldType},
		{Name: "UK10K_AF", Type: bigquery.FloatFieldType},
		{Name: "Interpro_domain", Type: bigquery.StringFieldType},
		{Name: "TOPMED_AF", Type: bigquery.FloatFieldType},
		{Name: "TW_AF", Type: bigquery.FloatFieldType},
		{Name: "Inheritance", Type: bigquery.StringFieldType},
		{Name: "Phenotype", Type: bigquery.StringFieldType},
		{Name: "Phenotype_MIM_number", Type: bigquery.StringFieldType},
		{Name: "Gene_MIM_Number", Type: bigquery.StringFieldType},
		{Name: "orphanet_gene_data_id", Type: bigquery.StringFieldType},
		{Name: "KG_EAS_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_AMR_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_AFR_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_EUR_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_SAS_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_AF", Type: bigquery.FloatFieldType},
		{Name: "KG_AN", Type: bigquery.IntegerFieldType},
		{Name: "ExAC_AF", Type: bigquery.FloatFieldType},
		{Name: "CLIN_SIG", Type: bigquery.StringFieldType},
		{Name: "ClinVar_Accession", Type: bigquery.StringFieldType},
		{Name: "ClinVar_CLNREVSTAT", Type: bigquery.StringFieldType},
		{Name: "ClinVar_Disease_Name", Type: bigquery.StringFieldType},
		{Name: "CLIN_CONF", Type: bigquery.StringFieldType},
		{Name: "MMCNT3", Type: bigquery.IntegerFieldType},
		{Name: "MMURI3", Type: bigquery.StringFieldType},
		{Name: "Refseq_prot", Type: bigquery.StringFieldType},
		{Name: "UniProtKB_AC", Type: bigquery.StringFieldType},
		{Name: "dbSNP_ID", Type: bigquery.StringFieldType},
		{Name: "GA_AF", Type: bigquery.FloatFieldType},
		{Name: "GA_AN", Type: bigquery.IntegerFieldType},
		{Name: "KJ_AF", Type: bigquery.FloatFieldType},
		{Name: "KJ_AN", Type: bigquery.IntegerFieldType},
		{Name: "GME_AF", Type: bigquery.FloatFieldType},
		{Name: "GME_AN", Type: bigquery.IntegerFieldType},
		{Name: "ESP6500_AF", Type: bigquery.FloatFieldType},
		{Name: "ESP6500_AN", Type: bigquery.IntegerFieldType},
		{Name: "ChinaMAP_AF", Type: bigquery.FloatFieldType},
		{Name: "mitomap_AF", Type: bigquery.FloatFieldType},
		{Name: "mitomap_aachange", Type: bigquery.StringFieldType},
		{Name: "mitomap_homoplasmy", Type: bigquery.StringFieldType},
		{Name: "mitomap_heteroplasmy", Type: bigquery.StringFieldType},
		{Name: "mitomap_PubmedIDs", Type: bigquery.StringFieldType},
		{Name: "mitomap_Disease", Type: bigquery.StringFieldType},
		{Name: "mitomap_DiseaseStatus", Type: bigquery.StringFieldType},
		{Name: "mitomap_HGFL", Type: bigquery.StringFieldType},
		{Name: "PVS1", Type: bigquery.IntegerFieldType},
		{Name: "PVS1_last_exon", Type: bigquery.IntegerFieldType},
		{Name: "PVS1_csq", Type: bigquery.IntegerFieldType},
		{Name: "PS1", Type: bigquery.IntegerFieldType},
		{Name: "PS1_missvar", Type: bigquery.IntegerFieldType},
		{Name: "PS1_novel", Type: bigquery.IntegerFieldType},
		{Name: "PS1_alternative_allele_matched", Type: bigquery.IntegerFieldType},
		{Name: "PS1_aa_matched", Type: bigquery.IntegerFieldType},
		{Name: "PM5", Type: bigquery.IntegerFieldType},
		{Name: "BA1", Type: bigquery.IntegerFieldType},
		{Name: "BA1_common_variants", Type: bigquery.IntegerFieldType},
		{Name: "BS1", Type: bigquery.IntegerFieldType},
		{Name: "BS1_af_exp", Type: bigquery.IntegerFieldType},
		{Name: "BS2", Type: bigquery.IntegerFieldType},
		{Name: "BS2_adult_onset", Type: bigquery.IntegerFieldType},
		{Name: "BS2_AD", Type: bigquery.IntegerFieldType},
		{Name: "BS2_AR", Type: bigquery.IntegerFieldType},
		{Name: "BS2_homo", Type: bigquery.IntegerFieldType},
		{Name: "BS2_heter", Type: bigquery.IntegerFieldType},
		{Name: "PM2", Type: bigquery.IntegerFieldType},
		{Name: "PM2_AD", Type: bigquery.IntegerFieldType},
		{Name: "PM2_AR", Type: bigquery.IntegerFieldType},
		{Name: "PM2_af_null", Type: bigquery.IntegerFieldType},
		{Name: "PM2_low_af", Type: bigquery.IntegerFieldType},
		{Name: "PM1", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_missense", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_interpro", Type: bigquery.IntegerFieldType},
		{Name: "PM1_benign", Type: bigquery.IntegerFieldType},
		{Name: "PM4", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_notrepeat_inframe", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_notrepeat_stoploss_frameshift", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_repeat_inframe", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_inframe", Type: bigquery.IntegerFieldType},
		{Name: "PM4_stoploss", Type: bigquery.IntegerFieldType},
		{Name: "PM4_frameshift", Type: bigquery.IntegerFieldType},
		{Name: "BP3", Type: bigquery.IntegerFieldType},
		{Name: "PP2", Type: bigquery.IntegerFieldType},
		{Name: "PP2_missenselist", Type: bigquery.IntegerFieldType},
		{Name: "BP1", Type: bigquery.IntegerFieldType},
		{Name: "BP1_truncatelist", Type: bigquery.IntegerFieldType},
		{Name: "PP3", Type: bigquery.IntegerFieldType},
		{Name: "PP3_path", Type: bigquery.IntegerFieldType},
		{Name: "PP3_severe_csq", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_cons", Type: bigquery.IntegerFieldType},
		{Name: "PP3_splicing", Type: bigquery.IntegerFieldType},
		{Name: "BP4", Type: bigquery.IntegerFieldType},
		{Name: "PP5", Type: bigquery.IntegerFieldType},
		{Name: "PP5_patho", Type: bigquery.IntegerFieldType},
		{Name: "BP6", Type: bigquery.IntegerFieldType},
		{Name: "BP6_benign", Type: bigquery.IntegerFieldType},
		{Name: "BP7", Type: bigquery.IntegerFieldType},
		{Name: "BP7_consequence", Type: bigquery.IntegerFieldType},
		{Name: "BP7_gerp", Type: bigquery.IntegerFieldType},
		{Name: "BP7_ada", Type: bigquery.IntegerFieldType},
		{Name: "BP7_rf", Type: bigquery.IntegerFieldType},
		{Name: "ACMG_Classification", Type: bigquery.StringFieldType},
	}
)

// AnnotationRecord ...
type AnnotationRecord struct {
	Chrom                           bigquery.NullString  `bigquery:"CHROM" json:"CHROM"`
	Pos                             bigquery.NullInt64   `bigquery:"POS" json:"POS"`
	ID                              bigquery.NullString  `bigquery:"ID" json:"ID"`
	Ref                             bigquery.NullString  `bigquery:"REF" json:"REF"`
	Alt                             bigquery.NullString  `bigquery:"ALT" json:"ALT"`
	Qual                            bigquery.NullFloat64 `bigquery:"QUAL" json:"QUAL"`
	Filter                          bigquery.NullString  `bigquery:"FILTER" json:"FILTER"`
	Gq                              bigquery.NullFloat64 `bigquery:"GQ" json:"GQ"`
	Dp                              bigquery.NullInt64   `bigquery:"DP" json:"DP"`
	Rd                              bigquery.NullInt64   `bigquery:"RD" json:"RD"`
	Ad                              bigquery.NullInt64   `bigquery:"AD" json:"AD"`
	Gt                              bigquery.NullString  `bigquery:"GT" json:"GT"`
	Ps                              bigquery.NullString  `bigquery:"PS" json:"PS"`
	GtAf                            bigquery.NullFloat64 `bigquery:"GT_AF" json:"GT_AF"`
	VariantClass                    bigquery.NullString  `bigquery:"VARIANT_CLASS" json:"VARIANT_CLASS"`
	Allele                          bigquery.NullString  `bigquery:"Allele" json:"Allele"`
	Consequence                     bigquery.NullString  `bigquery:"Consequence" json:"Consequence"`
	Impact                          bigquery.NullString  `bigquery:"IMPACT" json:"IMPACT"`
	Symbol                          bigquery.NullString  `bigquery:"SYMBOL" json:"SYMBOL"`
	Gene                            bigquery.NullString  `bigquery:"Gene" json:"Gene"`
	FeatureType                     bigquery.NullString  `bigquery:"Feature_type" json:"Feature_type"`
	Feature                         bigquery.NullString  `bigquery:"Feature" json:"Feature"`
	BioType                         bigquery.NullString  `bigquery:"Biotype" json:"Biotype"`
	Rank                            bigquery.NullString  `bigquery:"Rank" json:"Rank"`
	HGVSc                           bigquery.NullString  `bigquery:"HGVSc" json:"HGVSc"`
	HGVSp                           bigquery.NullString  `bigquery:"HGVSp" json:"HGVSp"`
	CDNAPosition                    bigquery.NullString  `bigquery:"cDNA_position" json:"cDNA_position"`
	CDSPosition                     bigquery.NullString  `bigquery:"CDS_position" json:"CDS_position"`
	ProteinPosition                 bigquery.NullString  `bigquery:"Protein_position" json:"Protein_position"`
	Distance                        bigquery.NullInt64   `bigquery:"Distance" json:"Distance"`
	ErrorsWarningsInfo              bigquery.NullString  `bigquery:"ERRORS_WARNINGS_INFO" json:"ERRORS_WARNINGS_INFO"`
	GnomAdAf                        bigquery.NullFloat64 `bigquery:"gnomAD_AF" json:"gnomAD_AF"`
	GnomAdAfrAf                     bigquery.NullFloat64 `bigquery:"gnomAD_AFR_AF" json:"gnomAD_AFR_AF"`
	GnomAdAmrAf                     bigquery.NullFloat64 `bigquery:"gnomAD_AMR_AF" json:"gnomAD_AMR_AF"`
	GnomAdAsjAf                     bigquery.NullFloat64 `bigquery:"gnomAD_ASJ_AF" json:"gnomAD_ASJ_AF"`
	GnomAdEasAf                     bigquery.NullFloat64 `bigquery:"gnomAD_EAS_AF" json:"gnomAD_EAS_AF"`
	GnomAdFinAf                     bigquery.NullFloat64 `bigquery:"gnomAD_FIN_AF" json:"gnomAD_FIN_AF"`
	GnomAdNfeAf                     bigquery.NullFloat64 `bigquery:"gnomAD_NFE_AF" json:"gnomAD_NFE_AF"`
	GnomAdOthAf                     bigquery.NullFloat64 `bigquery:"gnomAD_OTH_AF" json:"gnomAD_OTH_AF"`
	GnomAdSasAf                     bigquery.NullFloat64 `bigquery:"gnomAD_SAS_AF" json:"gnomAD_SAS_AF"`
	GnomAdAn                        bigquery.NullInt64   `bigquery:"gnomAD_AN" json:"gnomAD_AN"`
	GnomAdAnrAn                     bigquery.NullInt64   `bigquery:"gnomAD_ANR_AN" json:"gnomAD_ANR_AN"`
	GnomAdAmrAn                     bigquery.NullInt64   `bigquery:"gnomAD_AMR_AN" json:"gnomAD_AMR_AN"`
	GnomAdAsjAn                     bigquery.NullInt64   `bigquery:"gnomAD_ASJ_AN" json:"gnomAD_ASJ_AN"`
	GnomAdEasAn                     bigquery.NullInt64   `bigquery:"gnomAD_EAS_AN" json:"gnomAD_EAS_AN"`
	GnomAdFinAn                     bigquery.NullInt64   `bigquery:"gnomAD_FIN_AN" json:"gnomAD_FIN_AN"`
	GnomAdNfeAn                     bigquery.NullInt64   `bigquery:"gnomAD_NFE_AN" json:"gnomAD_NFE_AN"`
	GnomAdOthAn                     bigquery.NullInt64   `bigquery:"gnomAD_OTH_AN" json:"gnomAD_OTH_AN"`
	GnomAdSasAn                     bigquery.NullInt64   `bigquery:"gnomAD_SAS_AN" json:"gnomAD_SAS_AN"`
	GnomAdCovMean                   bigquery.NullFloat64 `bigquery:"gnomAD_cov_MEAN" json:"gnomAD_cov_MEAN"`
	GnomAdCovMedian                 bigquery.NullInt64   `bigquery:"gnomAD_cov_MEDIAN" json:"gnomAD_cov_MEDIAN"`
	GnomAdCovPct20X                 bigquery.NullFloat64 `bigquery:"gnomAD_cov_PCT_20X" json:"gnomAD_cov_PCT_20X"`
	GnomAdGCovMean                  bigquery.NullFloat64 `bigquery:"gnomAD_g_cov_MEAN" json:"gnomAD_g_cov_MEAN"`
	GnomAdGCovMedian                bigquery.NullInt64   `bigquery:"gnomAD_g_cov_MEDIAN" json:"gnomAD_g_cov_MEDIAN"`
	GnomAdGCovPct20X                bigquery.NullFloat64 `bigquery:"gnomAD_g_cov_PCT_20X" json:"gnomAD_g_cov_PCT_20X"`
	GnomAdGMtAfHom                  bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_AF_hom" json:"gnomAD_g_mt_AF_hom"`
	GnomAdGMtPopAfHomAfr            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_afr" json:"gnomAD_g_mt_pop_AF_hom_afr"`
	GnomAdGMtPopAfHomAmi            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_ami" json:"gnomAD_g_mt_pop_AF_hom_ami"`
	GnomAdGMtPopAfHomAmr            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_amr" json:"gnomAD_g_mt_pop_AF_hom_amr"`
	GnomAdGMtPopAfHomAsj            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_asj" json:"gnomAD_g_mt_pop_AF_hom_asj"`
	GnomAdGMtPopAfHomEas            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_eas" json:"gnomAD_g_mt_pop_AF_hom_eas"`
	GnomAdGMtPopAfHomFin            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_fin" json:"gnomAD_g_mt_pop_AF_hom_fin"`
	GnomAdGMtPopAfHomNfe            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_nfe" json:"gnomAD_g_mt_pop_AF_hom_nfe"`
	GnomAdGMtPopAfHomOth            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_oth" json:"gnomAD_g_mt_pop_AF_hom_oth"`
	GnomAdGMtPopAfHomSas            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_sas" json:"gnomAD_g_mt_pop_AF_hom_sas"`
	GnomAdGMtPopAfHomMid            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_hom_mid" json:"gnomAD_g_mt_pop_AF_hom_mid"`
	GnomAdGMtAfHet                  bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_AF_het" json:"gnomAD_g_mt_AF_het"`
	GnomAdGMtPopAfHetAfr            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_afr" json:"gnomAD_g_mt_pop_AF_het_afr"`
	GnomAdGMtPopAfHetAmi            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_ami" json:"gnomAD_g_mt_pop_AF_het_ami"`
	GnomAdGMtPopAfHetAmr            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_amr" json:"gnomAD_g_mt_pop_AF_het_amr"`
	GnomAdGMtPopAfHetAsj            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_asj" json:"gnomAD_g_mt_pop_AF_het_asj"`
	GnomAdGMtPopAfHetEas            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_eas" json:"gnomAD_g_mt_pop_AF_het_eas"`
	GnomAdGMtPopAfHetFin            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_fin" json:"gnomAD_g_mt_pop_AF_het_fin"`
	GnomAdGMtPopAfHetNfe            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_nfe" json:"gnomAD_g_mt_pop_AF_het_nfe"`
	GnomAdGMtPopAfHetOth            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_oth" json:"gnomAD_g_mt_pop_AF_het_oth"`
	GnomAdGMtPopAfHetSas            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_sas" json:"gnomAD_g_mt_pop_AF_het_sas"`
	GnomAdGMtPopAfHetMid            bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_pop_AF_het_mid" json:"gnomAD_g_mt_pop_AF_het_mid"`
	GnomAdGMtMitotipScore           bigquery.NullFloat64 `bigquery:"gnomAD_g_mt_mitotip_score" json:"gnomAD_g_mt_mitotip_score"`
	GnomAdGAf                       bigquery.NullFloat64 `bigquery:"gnomAD_g_AF" json:"gnomAD_g_AF"`
	GnomAdGAfAfr                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_afr" json:"gnomAD_g_AF_afr"`
	GnomAdGAfAmi                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_ami" json:"gnomAD_g_AF_ami"`
	GnomAdGAfAmr                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_amr" json:"gnomAD_g_AF_amr"`
	GnomAdGAfAsj                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_asj" json:"gnomAD_g_AF_asj"`
	GnomAdGAfEas                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_eas" json:"gnomAD_g_AF_eas"`
	GnomAdGAfFin                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_fin" json:"gnomAD_g_AF_fin"`
	GnomAdGAfMid                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_mid" json:"gnomAD_g_AF_mid"`
	GnomAdGAfNfe                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_nfe" json:"gnomAD_g_AF_nfe"`
	GnomAdGAfOth                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_oth" json:"gnomAD_g_AF_oth"`
	GnomAdGAfSas                    bigquery.NullFloat64 `bigquery:"gnomAD_g_AF_sas" json:"gnomAD_g_AF_sas"`
	AdaScore                        bigquery.NullFloat64 `bigquery:"ada_score" json:"ada_score"`
	RfScore                         bigquery.NullFloat64 `bigquery:"rf_score" json:"rf_score"`
	SpliceAIDsAg                    bigquery.NullFloat64 `bigquery:"SpliceAI_DS_AG" json:"SpliceAI_DS_AG"`
	SpliceAIDsAl                    bigquery.NullFloat64 `bigquery:"SpliceAI_DS_AL" json:"SpliceAI_DS_AL"`
	SpliceAIDsDg                    bigquery.NullFloat64 `bigquery:"SpliceAI_DS_DG" json:"SpliceAI_DS_DG"`
	SpliceAIDsDl                    bigquery.NullFloat64 `bigquery:"SpliceAI_DS_DL" json:"SpliceAI_DS_DL"`
	SpliceAIDpAg                    bigquery.NullInt64   `bigquery:"SpliceAI_DP_AG" json:"SpliceAI_DP_AG"`
	SpliceAIDpAl                    bigquery.NullInt64   `bigquery:"SpliceAI_DP_AL" json:"SpliceAI_DP_AL"`
	SpliceAIDpDg                    bigquery.NullInt64   `bigquery:"SpliceAI_DP_DG" json:"SpliceAI_DP_DG"`
	SpliceAIDpDl                    bigquery.NullInt64   `bigquery:"SpliceAI_DP_DL" json:"SpliceAI_DP_DL"`
	SiftScore                       bigquery.NullFloat64 `bigquery:"SIFT_score" json:"SIFT_score"`
	SiftPred                        bigquery.NullString  `bigquery:"SIFT_pred" json:"SIFT_pred"`
	Sift4gScore                     bigquery.NullFloat64 `bigquery:"SIFT4G_score" json:"SIFT4G_score"`
	Sift4gPred                      bigquery.NullString  `bigquery:"SIFT4G_pred" json:"SIFT4G_pred"`
	MetaLRScore                     bigquery.NullFloat64 `bigquery:"MetaLR_score" json:"MetaLR_score"`
	MetaLRPred                      bigquery.NullString  `bigquery:"MetaLR_pred" json:"MetaLR_pred"`
	MetaSVMScore                    bigquery.NullFloat64 `bigquery:"MetaSVM_score" json:"MetaSVM_score"`
	MetaSVMPred                     bigquery.NullString  `bigquery:"MetaSVM_pred" json:"MetaSVM_pred"`
	RevelScore                      bigquery.NullFloat64 `bigquery:"REVEL_score" json:"REVEL_score"`
	Polyphen                        bigquery.NullFloat64 `bigquery:"Polyphen" json:"Polyphen"`
	PolyphenPred                    bigquery.NullString  `bigquery:"Polyphen_pred" json:"Polyphen_pred"`
	FathmmScore                     bigquery.NullFloat64 `bigquery:"FATHMM_score" json:"FATHMM_score"`
	FathmmPred                      bigquery.NullString  `bigquery:"FATHMM_pred" json:"FATHMM_pred"`
	MutationAssessorScore           bigquery.NullFloat64 `bigquery:"MutationAssessor_score" json:"MutationAssessor_score"`
	MutationAssessorPred            bigquery.NullString  `bigquery:"MutationAssessor_pred" json:"MutationAssessor_pred"`
	ProveanScore                    bigquery.NullFloat64 `bigquery:"PROVEAN_score" json:"PROVEAN_score"`
	ProveanPred                     bigquery.NullString  `bigquery:"PROVEAN_pred" json:"PROVEAN_pred"`
	CaddRaw                         bigquery.NullFloat64 `bigquery:"CADD_raw" json:"CADD_raw"`
	CaddPhred                       bigquery.NullFloat64 `bigquery:"CADD_phred" json:"CADD_phred"`
	MCapScore                       bigquery.NullFloat64 `bigquery:"M_CAP_score" json:"M_CAP_score"`
	MCapPred                        bigquery.NullString  `bigquery:"M_CAP_pred" json:"M_CAP_pred"`
	RevelRankscore                  bigquery.NullFloat64 `bigquery:"REVEL_rankscore" json:"REVEL_rankscore"`
	Esp6500AaAf                     bigquery.NullFloat64 `bigquery:"ESP6500_AA_AF" json:"ESP6500_AA_AF"`
	Esp6500EaAf                     bigquery.NullFloat64 `bigquery:"ESP6500_EA_AF" json:"ESP6500_EA_AF"`
	BayesDelAddAFScore              bigquery.NullFloat64 `bigquery:"BayesDel_addAF_score" json:"BayesDel_addAF_score"`
	BayesDelAddAFPred               bigquery.NullString  `bigquery:"BayesDel_addAF_pred" json:"BayesDel_addAF_pred"`
	GERPppNR                        bigquery.NullFloat64 `bigquery:"GERPpp_NR" json:"GERPpp_NR"`
	GERPppRS                        bigquery.NullFloat64 `bigquery:"GERPpp_RS" json:"GERPpp_RS"`
	SiPhy29wayLogOdds               bigquery.NullFloat64 `bigquery:"SiPhy_29way_logOdds" json:"SiPhy_29way_logOdds"`
	SiPhy29wayPi                    bigquery.NullString  `bigquery:"SiPhy_29way_pi" json:"SiPhy_29way_pi"`
	OeSyn                           bigquery.NullFloat64 `bigquery:"oe_syn" json:"oe_syn"`
	OeMis                           bigquery.NullFloat64 `bigquery:"oe_mis" json:"oe_mis"`
	OeLof                           bigquery.NullFloat64 `bigquery:"oe_lof" json:"oe_lof"`
	SynZ                            bigquery.NullFloat64 `bigquery:"syn_z" json:"syn_z"`
	MisZ                            bigquery.NullFloat64 `bigquery:"mis_z" json:"mis_z"`
	PLI                             bigquery.NullFloat64 `bigquery:"pLI" json:"pLI"`
	Uk10kAf                         bigquery.NullFloat64 `bigquery:"UK10K_AF" json:"UK10K_AF"`
	InterproDomain                  bigquery.NullString  `bigquery:"Interpro_domain" json:"Interpro_domain"`
	TopmedAf                        bigquery.NullFloat64 `bigquery:"TOPMED_AF" json:"TOPMED_AF"`
	TwAf                            bigquery.NullFloat64 `bigquery:"TW_AF" json:"TW_AF"`
	Inheritance                     bigquery.NullString  `bigquery:"Inheritance" json:"Inheritance"`
	Phenotype                       bigquery.NullString  `bigquery:"Phenotype" json:"Phenotype"`
	PhenotypeMimNumber              bigquery.NullString  `bigquery:"Phenotype_MIM_number" json:"Phenotype_MIM_number"`
	GeneMimNumber                   bigquery.NullString  `bigquery:"Gene_MIM_Number" json:"Gene_MIM_Number"`
	OrphanetDisease                 bigquery.NullString  `bigquery:"orphanet_disease" json:"orphanet_disease"`
	OrphanetOrphaID                 bigquery.NullString  `bigquery:"orphanet_orpha_id" json:"orphanet_orpha_id"`
	OrphanetInheritance             bigquery.NullString  `bigquery:"orphanet_inheritance" json:"orphanet_inheritance"`
	OrphanetGeneDataID              bigquery.NullString  `bigquery:"orphanet_gene_data_id" json:"orphanet_gene_data_id"`
	KgEasAf                         bigquery.NullFloat64 `bigquery:"KG_EAS_AF" json:"KG_EAS_AF"`
	KgAmrAf                         bigquery.NullFloat64 `bigquery:"KG_AMR_AF" json:"KG_AMR_AF"`
	KgAfrAf                         bigquery.NullFloat64 `bigquery:"KG_AFR_AF" json:"KG_AFR_AF"`
	KgEurAf                         bigquery.NullFloat64 `bigquery:"KG_EUR_AF" json:"KG_EUR_AF"`
	KgSasAf                         bigquery.NullFloat64 `bigquery:"KG_SAS_AF" json:"KG_SAS_AF"`
	KgAf                            bigquery.NullFloat64 `bigquery:"KG_AF" json:"KG_AF"`
	KgAn                            bigquery.NullInt64   `bigquery:"KG_AN" json:"KG_AN"`
	ExacAf                          bigquery.NullFloat64 `bigquery:"ExAC_AF" json:"ExAC_AF"`
	ClinSig                         bigquery.NullString  `bigquery:"CLIN_SIG" json:"CLIN_SIG"`
	ClinVarAccession                bigquery.NullString  `bigquery:"ClinVar_Accession" json:"ClinVar_Accession"`
	ClinVarClnrevstat               bigquery.NullString  `bigquery:"ClinVar_CLNREVSTAT" json:"ClinVar_CLNREVSTAT"`
	ClinVarDiseaseName              bigquery.NullString  `bigquery:"ClinVar_Disease_Name" json:"ClinVar_Disease_Name"`
	ClinConf                        bigquery.NullString  `bigquery:"CLIN_CONF" json:"CLIN_CONF"`
	Mmcnt3                          bigquery.NullInt64   `bigquery:"MMCNT3" json:"MMCNT3"`
	Mmuri3                          bigquery.NullString  `bigquery:"MMURI3" json:"MMURI3"`
	RefseqProt                      bigquery.NullString  `bigquery:"Refseq_prot" json:"Refseq_prot"`
	UniProtKbAc                     bigquery.NullString  `bigquery:"UniProtKB_AC" json:"UniProtKB_AC"`
	DbSnpID                         bigquery.NullString  `bigquery:"dbSNP_ID" json:"dbSNP_ID"`
	GaAf                            bigquery.NullFloat64 `bigquery:"GA_AF" json:"GA_AF"`
	GaAn                            bigquery.NullInt64   `bigquery:"GA_AN" json:"GA_AN"`
	KjAf                            bigquery.NullFloat64 `bigquery:"KJ_AF" json:"KJ_AF"`
	KjAn                            bigquery.NullInt64   `bigquery:"KJ_AN" json:"KJ_AN"`
	GmeAf                           bigquery.NullFloat64 `bigquery:"GME_AF" json:"GME_AF"`
	GmeAn                           bigquery.NullInt64   `bigquery:"GME_AN" json:"GME_AN"`
	Esp6500Af                       bigquery.NullFloat64 `bigquery:"ESP6500_AF" json:"ESP6500_AF"`
	Esp6500An                       bigquery.NullInt64   `bigquery:"ESP6500_AN" json:"ESP6500_AN"`
	ChinaMAPAf                      bigquery.NullFloat64 `bigquery:"ChinaMAP_AF" json:"ChinaMAP_AF"`
	MitomapAF                       bigquery.NullFloat64 `bigquery:"mitomap_AF" json:"mitomap_AF"`
	MitomapAachange                 bigquery.NullString  `bigquery:"mitomap_aachange" json:"mitomap_aachange"`
	MitomapHomoplasmy               bigquery.NullString  `bigquery:"mitomap_homoplasmy" json:"mitomap_homoplasmy"`
	MitomapHeteroplasmy             bigquery.NullString  `bigquery:"mitomap_heteroplasmy" json:"mitomap_heteroplasmy"`
	MitomapPubmedIDs                bigquery.NullString  `bigquery:"mitomap_PubmedIDs" json:"mitomap_PubmedIDs"`
	MitomapDisease                  bigquery.NullString  `bigquery:"mitomap_Disease" json:"mitomap_Disease"`
	MitomapDiseaseStatus            bigquery.NullString  `bigquery:"mitomap_DiseaseStatus" json:"mitomap_DiseaseStatus"`
	MitomapHGFL                     bigquery.NullString  `bigquery:"mitomap_HGFL" json:"mitomap_HGFL"`
	Pvs1                            bigquery.NullInt64   `bigquery:"PVS1" json:"PVS1"`
	Pvs1LastExon                    bigquery.NullInt64   `bigquery:"PVS1_last_exon" json:"PVS1_last_exon"`
	Pvs1Csq                         bigquery.NullInt64   `bigquery:"PVS1_csq" json:"PVS1_csq"`
	Ps1                             bigquery.NullInt64   `bigquery:"PS1" json:"PS1"`
	Ps1Missvar                      bigquery.NullInt64   `bigquery:"PS1_missvar" json:"PS1_missvar"`
	Ps1Novel                        bigquery.NullInt64   `bigquery:"PS1_novel" json:"PS1_novel"`
	Ps1AlternativeAlleleMatched     bigquery.NullInt64   `bigquery:"PS1_alternative_allele_matched" json:"PS1_alternative_allele_matched"`
	Ps1AaMatched                    bigquery.NullInt64   `bigquery:"PS1_aa_matched" json:"PS1_aa_matched"`
	Pm5                             bigquery.NullInt64   `bigquery:"PM5" json:"PM5"`
	Ba1                             bigquery.NullInt64   `bigquery:"BA1" json:"BA1"`
	Ba1CommonVariants               bigquery.NullInt64   `bigquery:"BA1_common_variants" json:"BA1_common_variants"`
	Bs1                             bigquery.NullInt64   `bigquery:"BS1" json:"BS1"`
	Bs1AfExp                        bigquery.NullInt64   `bigquery:"BS1_af_exp" json:"BS1_af_exp"`
	Bs2                             bigquery.NullInt64   `bigquery:"BS2" json:"BS2"`
	Bs2AdultOnset                   bigquery.NullInt64   `bigquery:"BS2_adult_onset" json:"BS2_adult_onset"`
	Bs2Ad                           bigquery.NullInt64   `bigquery:"BS2_AD" json:"BS2_AD"`
	Bs2Ar                           bigquery.NullInt64   `bigquery:"BS2_AR" json:"BS2_AR"`
	Bs2Homo                         bigquery.NullInt64   `bigquery:"BS2_homo" json:"BS2_homo"`
	Bs2Heter                        bigquery.NullInt64   `bigquery:"BS2_heter" json:"BS2_heter"`
	Pm2                             bigquery.NullInt64   `bigquery:"PM2" json:"PM2"`
	Pm2Ad                           bigquery.NullInt64   `bigquery:"PM2_AD" json:"PM2_AD"`
	Pm2Ar                           bigquery.NullInt64   `bigquery:"PM2_AR" json:"PM2_AR"`
	Pm2AfNull                       bigquery.NullInt64   `bigquery:"PM2_af_null" json:"PM2_af_null"`
	Pm2LowAf                        bigquery.NullInt64   `bigquery:"PM2_low_af" json:"PM2_low_af"`
	Pm1                             bigquery.NullInt64   `bigquery:"PM1" json:"PM1"`
	AcmgMissense                    bigquery.NullInt64   `bigquery:"ACMG_missense" json:"ACMG_missense"`
	AcmgInterpro                    bigquery.NullInt64   `bigquery:"ACMG_interpro" json:"ACMG_interpro"`
	Pm1Benign                       bigquery.NullInt64   `bigquery:"PM1_benign" json:"PM1_benign"`
	Pm4                             bigquery.NullInt64   `bigquery:"PM4" json:"PM4"`
	ACMGNotrepeatInframe            bigquery.NullInt64   `bigquery:"ACMG_notrepeat_inframe" json:"ACMG_notrepeat_inframe"`
	ACMGNotrepeatStoplossFrameshift bigquery.NullInt64   `bigquery:"ACMG_notrepeat_stoploss_frameshift" json:"ACMG_notrepeat_stoploss_frameshift"`
	ACMGRepeatInframe               bigquery.NullInt64   `bigquery:"ACMG_repeat_inframe" json:"ACMG_repeat_inframe"`
	ACMGInframe                     bigquery.NullInt64   `bigquery:"ACMG_inframe" json:"ACMG_inframe"`
	Pm4Stoploss                     bigquery.NullInt64   `bigquery:"PM4_stoploss" json:"PM4_stoploss"`
	Pm4Frameshift                   bigquery.NullInt64   `bigquery:"PM4_frameshift" json:"PM4_frameshift"`
	Bp3                             bigquery.NullInt64   `bigquery:"BP3" json:"BP3"`
	Pp2                             bigquery.NullInt64   `bigquery:"PP2" json:"PP2"`
	Pp2Missenselist                 bigquery.NullInt64   `bigquery:"PP2_missenselist" json:"PP2_missenselist"`
	Bp1                             bigquery.NullInt64   `bigquery:"BP1" json:"BP1"`
	Bp1Truncatelist                 bigquery.NullInt64   `bigquery:"BP1_truncatelist" json:"BP1_truncatelist"`
	Pp3                             bigquery.NullInt64   `bigquery:"PP3" json:"PP3"`
	Pp3Path                         bigquery.NullInt64   `bigquery:"PP3_path" json:"PP3_path"`
	Pp3SevereCsq                    bigquery.NullInt64   `bigquery:"PP3_severe_csq" json:"PP3_severe_csq"`
	AcmgCons                        bigquery.NullInt64   `bigquery:"ACMG_cons" json:"ACMG_cons"`
	Pp3Splicing                     bigquery.NullInt64   `bigquery:"PP3_splicing" json:"PP3_splicing"`
	Bp4                             bigquery.NullInt64   `bigquery:"BP4" json:"BP4"`
	Pp5                             bigquery.NullInt64   `bigquery:"PP5" json:"PP5"`
	Pp5Patho                        bigquery.NullInt64   `bigquery:"PP5_patho" json:"PP5_patho"`
	Bp6                             bigquery.NullInt64   `bigquery:"BP6" json:"BP6"`
	Bp6Benign                       bigquery.NullInt64   `bigquery:"BP6_benign" json:"BP6_benign"`
	Bp7                             bigquery.NullInt64   `bigquery:"BP7" json:"BP7"`
	Bp7Consequence                  bigquery.NullInt64   `bigquery:"BP7_consequence" json:"BP7_consequence"`
	Bp7Gerp                         bigquery.NullInt64   `bigquery:"BP7_gerp" json:"BP7_gerp"`
	Bp7Ada                          bigquery.NullInt64   `bigquery:"BP7_ada" json:"BP7_ada"`
	Bp7Rf                           bigquery.NullInt64   `bigquery:"BP7_rf" json:"BP7_rf"`
	AcmgClassification              bigquery.NullString  `bigquery:"ACMG_Classification" json:"ACMG_Classification"`
	PvdbPFilter                     bigquery.NullString  `bigquery:"PVDB_P_FILTER" json:"PVDB_P_FILTER"`
	PvdbPFMissing                   bigquery.NullFloat64 `bigquery:"PVDB_P_F_MISSING" json:"PVDB_P_F_MISSING"`
	PvdbPAc                         bigquery.NullInt64   `bigquery:"PVDB_P_AC" json:"PVDB_P_AC"`
	PvdbPAn                         bigquery.NullInt64   `bigquery:"PVDB_P_AN" json:"PVDB_P_AN"`
	PvdbPAf                         bigquery.NullFloat64 `bigquery:"PVDB_P_AF" json:"PVDB_P_AF"`
	PvdbPDp                         bigquery.NullInt64   `bigquery:"PVDB_P_DP" json:"PVDB_P_DP"`
	PvdbPAcHet                      bigquery.NullInt64   `bigquery:"PVDB_P_AC_Het" json:"PVDB_P_AC_Het"`
	PvdbPAcHom                      bigquery.NullInt64   `bigquery:"PVDB_P_AC_Hom" json:"PVDB_P_AC_Hom"`
	PvdbPAcHemi                     bigquery.NullInt64   `bigquery:"PVDB_P_AC_Hemi" json:"PVDB_P_AC_Hemi"`
	PvdbSFilter                     bigquery.NullString  `bigquery:"PVDB_S_FILTER" json:"PVDB_S_FILTER"`
	PvdbSFMissing                   bigquery.NullFloat64 `bigquery:"PVDB_S_F_MISSING" json:"PVDB_S_F_MISSING"`
	PvdbSAc                         bigquery.NullInt64   `bigquery:"PVDB_S_AC" json:"PVDB_S_AC"`
	PvdbSAn                         bigquery.NullInt64   `bigquery:"PVDB_S_AN" json:"PVDB_S_AN"`
	PvdbSAf                         bigquery.NullFloat64 `bigquery:"PVDB_S_AF" json:"PVDB_S_AF"`
	PvdbSDp                         bigquery.NullInt64   `bigquery:"PVDB_S_DP" json:"PVDB_S_DP"`
	PvdbSAcHet                      bigquery.NullInt64   `bigquery:"PVDB_S_AC_Het" json:"PVDB_S_AC_Het"`
	PvdbSAcHom                      bigquery.NullInt64   `bigquery:"PVDB_S_AC_Hom" json:"PVDB_S_AC_Hom"`
	PvdbSAcHemi                     bigquery.NullInt64   `bigquery:"PVDB_S_AC_Hemi" json:"PVDB_S_AC_Hemi"`
	PvdbAFilter                     bigquery.NullString  `bigquery:"PVDB_A_FILTER" json:"PVDB_A_FILTER"`
	PvdbAFMissing                   bigquery.NullFloat64 `bigquery:"PVDB_A_F_MISSING" json:"PVDB_A_F_MISSING"`
	PvdbAAc                         bigquery.NullInt64   `bigquery:"PVDB_A_AC" json:"PVDB_A_AC"`
	PvdbAAn                         bigquery.NullInt64   `bigquery:"PVDB_A_AN" json:"PVDB_A_AN"`
	PvdbAAf                         bigquery.NullFloat64 `bigquery:"PVDB_A_AF" json:"PVDB_A_AF"`
	PvdbADp                         bigquery.NullInt64   `bigquery:"PVDB_A_DP" json:"PVDB_A_DP"`
	PvdbAAcHet                      bigquery.NullInt64   `bigquery:"PVDB_A_AC_Het" json:"PVDB_A_AC_Het"`
	PvdbAAcHom                      bigquery.NullInt64   `bigquery:"PVDB_A_AC_Hom" json:"PVDB_A_AC_Hom"`
	PvdbAAcHemi                     bigquery.NullInt64   `bigquery:"PVDB_A_AC_Hemi" json:"PVDB_A_AC_Hemi"`
}
